steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile
      - -t
      - gcr.io/$PROJECT_ID/fraudai-backend:latest
      - .
images:
  - gcr.io/$PROJECT_ID/fraudai-backend:latest
options:
  logging: CLOUD_LOGGING_ONLY
